language: cpp
jobs:
  include:
  - os: osx
    scripts:
    - cmake -H. -B_build
    - cmake --build _build
    - cd _build
    - cpack -G DragNDrop
    - cd ..
  - os: linux
    scripts:
    - cmake -H. -B_build
    - cmake --build _build
    - cd _build
    - cpack -G DEB
    - cpack -G RPM
    - cd ..
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - cmake
    - cmake-data
    - clang-3.7
    - g++-7
    - rpm
deploy:
  -provider: releases
  -api_key: 47878be1279814a1e282082bc90e519eab35fea9
  -file_glob: true
  -file: 
   - ./_build/solver-0.1.0.-Darwin.dmg
   - ./_build/solver-0.1.0.-Linux.deb
   - ./_build/solver-0.1.0.-Linux.rpm
  skip_cleanup: true
  on:
    tags: true


